char_sheet/urls.py
from django.urls import path

from . import views

app_name = 'char_sheet'
urlpatterns = [
	# ex: /char_sheet/
	path('', views.index, name='index'),
	# ex: /char_sheet/3/
	path('<int:player_id>/', views.detail, name='detail'),
	#path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	# ex: /char_sheet/3/2/
	path('<int:player_id>/character', views.char_detail, name='char_detail')

]

dnd_proj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('char_sheet/', include('char_sheet.urls')),
    path('admin/', admin.site.urls),
]

char_sheet/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Player(models.Model):
	player_name = models.CharField(max_length=50)

	def __str__(self):
		return self.player_name

# Implementation for backgrounds TBD
#class 5e_Background(models.Model):


class Charakter(models.Model):

	class Class_Choices(models.TextChoices):
		BARBARIAN = 'BARBARIAN', _('Barbarian')
		BARD = 'BARD', _('Bard')
		CLERIC = 'CLERIC', _('Cleric')
		DRUID = 'DRUID', _('Druid')
		FIGHTER = 'FIGHTER', _('Fighter')
		MONK = 'MONK', _('Monk')
		PALADIN = 'PALADIN', _('Paladin')
		RANGER = 'RANGER', _('Ranger')
		ROGUE = 'ROGUE', _('Rogue')
		SORCERER = 'SORCERER', _('Sorcerer')
		WARLOCK = 'WARLOCK', _('Warlock')
		WIZARD = 'WIZARD', _('Wizard')

	class Race_Choices(models.TextChoices):
		DWARF = 'DWARF', _('Dwarf')
		ELF = 'ELF', _('Elf')
		HALFLING = 'HALFLING', _('Halfling')
		HUMAN = 'HUMAN', _('Human')
		DRAGONBORN = 'DRAGONBORN', _('Dragonborn')
		GNOME = 'GNOME', _('Gnome')
		HALFELF = 'HALF-ELF', _('Half-Elf')
		HALFORC = 'HALF-ORC', _('Half-Orc')
		TIEFLING = 'TIEFLING', _('Tiefling')
		GOLIATH = 'GOLIATH', _('Goliath')

	class Alignment_Choices(models.TextChoices):
		LAWFUL_GOOD = 'LG', _('Lawful Good')
		LAWFUL_NEUTRAL = 'LN', _('Lawful Neutral')
		LAWFUL_EVIL = 'LE', _('Lawful Evil')
		NEUTRAL_GOOD = 'NG', _('Neutral Good')
		TRUE_NEUTRAL = 'TN', _('True Neutral')
		NEUTRAL_EVIL = 'NE', _('Neutral Evil')
		CHAOTIC_GOOD = 'CG', _('Chaotic Good')
		CHAOTIC_NEUTRAL = 'CN', _('Chaotic Neutral')
		CHAOTIC_EVIL = 'CE', _('Chaotic Evil')

	player = models.ForeignKey(Player, on_delete=models.CASCADE)
	char_name = models.CharField(max_length=50)
	klasse = models.CharField(max_length=10, choices=Class_Choices.choices)			#class
	niveau = models.PositiveSmallIntegerField(default=1)							#level
	rasse = models.CharField(max_length=12, choices=Race_Choices.choices)			#race
	herkunft = models.CharField(max_length= 25)										#background
	ausrichtung = models.CharField(max_length=2, choices=Alignment_Choices.choices)	#alignment
	exp = models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.char_name

char_sheet/forms.py
from django import forms
from django.forms import ModelForm

from .models import Player, Charakter

class PlayerForm(ModelForm):
	class Meta:
		model = Player
		fields = ['player_name']

class CharakterForm(ModelForm):
	class Meta:
		model = Charakter
		fields = ['char_name', 'rasse', 'klasse', 'herkunft', 'ausrichtung']

char_sheet/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.views import generic

from .models import Player, Charakter
from .forms import PlayerForm, CharakterForm
# Create your views here.

def add_player(pl_name):
	np = Player(player_name = pl_name)
	np.save()

def index(request):
	if 'player_name' in request.POST:
		add_player(request.POST['player_name'])

	player_list = Player.objects.all()
	charakter_list = Charakter.objects.all()
	return render(request, 'char_sheet/index.html', {'player_list': player_list, 'charakter_list': charakter_list})

def detail(request, player_id):
	current_player = get_object_or_404(Player, pk=player_id)
	charakter_list = Charakter.objects.filter(player=get_object_or_404(Player, pk=player_id))
	return render(request, 'char_sheet/player_detail.html', {'player': current_player, 'charakter_list': charakter_list,})

#class DetailView(generic.DetailView):
#	model = Player
#	charakter_list = Charakter.objects.filter(player=get_object_or_404(Player, pk))


def char_detail(request, player_id):
	current_player = get_object_or_404(Player, pk=player_id)
	
	if request.method == 'POST':
		charakter_form = CharakterForm(request.POST)

		if charakter_form.is_valid():
			new_ch = charakter_form.save()
			player_list = Player.objects.all()
			charakter_list = Charakter.objects.all()
			return render(request, 'char_sheet/index.html', {'player_list': player_list, 'charakter_list': charakter_list})
	else:
		charakter_form = CharakterForm()
	
	charakter_list = Charakter.objects.filter(player=current_player)
	return render(request, 'char_sheet/char_detail.html', {'player': current_player, 'charakter_list': charakter_list, 'charakter_form': charakter_form})

char_sheet/templates/char_sheet/char_detail.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Index</title>
</head>
<body>
	<h1>{{ charakter.char_name }}</h1>
	<li><a href="{% url 'char_sheet:index' %}">Return to Main Page</a></li>


	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form method="post">
		{% csrf_token %}
		{{ charakter_form }}
		<input type="submit" value="Submit">
	</form>

</body>
</html>

char_sheet/templates/char_sheet/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'char_sheet/style.css' %}"/>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Index</title>
</head>
<body>
<script>
	function set_pl_div_vis() {
		p_div = document.getElementById("player_div");
		if (p_div.style.display == "block")
			p_div.style.display = "none";
		else
			p_div.style.display = "block";
			document.getElementById("player_name").focus();
	}

	function set_ch_div_vis() {
		ch_div = document.getElementById("char_div");
		if (ch_div.style.display == "block")
			ch_div.style.display = "none";
		else
			ch_div.style.display = "block";
			document.getElementById("char_name").focus();
	}
</script>

	<h1>Players</h1>

	{% if player_list %}
		<ul class="pc_list" id="pl_list">
		{% for player in player_list %}
			<div>
			<li>
				<button class=action_button onclick="set_ch_div_vis()">New Character</button>
				<a href="{% url 'char_sheet:char_detail' player.id %}">{{ player.player_name }}</a>
			</li>
			</div>
			<div id="char_div">
					<form action="{% url 'char_sheet:char_detail' player.id %}" method="post">
						{% csrf_token %}
						<label for="char_name">Character Name</label>
						<input type="text" name="char_name" id="char_name" placeholder="Enter Chacter Name" required>
						<label for="klasse">Class</label>
						<input type="text" name="klasse" id="klasse" placeholder="Enter Chacter Class" required>
						<label for="rasse">Race</label>
						<input type="text" name="rasse" id="rasse" placeholder="Enter Chacter Race" required>
						<input class="action_button" type="submit" value="Submit">
					</form>
			</div>
			<div>
			<ul class="pc_list" id="ch_list">
			{% for charakter in charakter_list %}
				{% if charakter.player == player %}
					<div>
					<li><a href="{% url 'char_sheet:char_detail' player.id %}">{{ charakter.char_name }}</a>
					<p class="ch_expanded">Lvl {{ charakter.niveau }} {{ charakter.rasse }} {{charakter.klasse }}</p></li>
					</div>
				{% endif %}
			{% endfor %}
			</ul>
			</div>
		{% endfor %}
		</ul>
	{% else %}
		<p>No players have been created</p>
	{% endif %}

	<button class="action_button" id="pl_visible" onclick="set_pl_div_vis()">New Player</button>
	<div id="player_div">
		<form method="post">
			{% csrf_token %}
			<label for="player_name">Player Name:</label>
			<input type="text" name="player_name" id="player_name" placeholder="Enter player name" required>
			<input class="action_button" type="submit" value="Submit">
		</form>
	</div>

</body>
</html>

char_sheet/templates/char_sheet/player_detail.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Index</title>
</head>
<body>
	<h1>{{ player.player_name }}</h1>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	{% if charakter_list %}
	<ul>
	{% for charakter in player.charakter_set.all %}
		<li>{{ charakter.char_name }}</li>
	{% endfor %}
	</ul>
	{% endif %}

	<form action="{% url 'char_sheet:char_detail' player.id %}" method="post">
		{% csrf_token %}
		<label for="char_name">Character Name</label>
		<input type="text" name="char_name" id="char_name" placeholder="Enter Chacter Name">
		<label for="klasse">Class</label>
		<input type="text" name="klasse" id="klasse" placeholder="Enter Chacter Class">
		<label for="rasse">Race</label>
		<input type="text" name="rasse" id="rasse" placeholder="Enter Chacter Race">
		<input type="submit" value="New Character">
	</form>

</body>
</html>